### PR TITLE
Updated setting default locale for api documentation

### PR DESCRIPTION
**Pull request by DmitryKK**

### CODE REVIEW

**Comment by iNecas** [comment]
What is the issue this PR fixes? Just to understand better the reasoning behind the change?

**Comment by DmitryKK** [comment]
@iNecas, the fact is that configuration `Apipie.configuration.default_locale' is not working. Api documentation shows default language by `I18n.default locale`. You may check

**Comment by iNecas** [comment]
Oh, I see. Makes sense then :) Merging

**Comment by iNecas** [comment]
apipie-0.5.2 released, including this change.

**Comment by Haniyya** [comment]
This seems to result in a breaking change:
If you set your `default_locale` to something other than 'en' and defined your api, this change will alter all the links in the documentation to use a locale (like `users/1.de.html`) which leads to non-existant documentation errors for everything.
Workaround is to manually remove the locale from the urls, which leads you back to a working state.

**Pull request merged**
