### PR TITLE
Refactor Swagger generator

### PR DESCRIPTION
**Pull request by PanosCodes**
## Why
In the spirit of https://github.com/Apipie/apipie-rails/pull/803 and https://github.com/Apipie/apipie-rails/pull/810 this PR is an attempt to break down the Swagger generator into smaller modules.

## How

The generator has only the three entrypoint class methods(`generate_from_resources`, `json_schema_for_method_response` & `json_schema_for_self_describing_class` and the rest of the code has been moved to smaller files.

## Thoughts
Again, although this PR adds more lines than it removes, I think it makes it easer to navigate and test the generator code.

### CODE REVIEW

**Review by mathieujobin — COMMENTED** [review]
< 👀 >

**Comment by mathieujobin** [comment]
Sorry if I am not able to review this one faster... its quite large, and I'm having some trouble finding the time...

Also, there is a merge conflict if you want to take a look...

**Comment by PanosCodes** [comment]
No worries. I tried to brake the refactor into smaller parts but this one got out of hand, sorry 😅
Once you complete the review feel free to ping be, since the `.rubocop_todo.yml` might change before merging this one

**Review by mathieujobin — COMMENTED** [review]
Maybe what would help is some documentation around this refactor. 
what it allows. Why so many new files. why new functionality it brings?

**Comment by PanosCodes** [comment]
Could we reopen this PR ?, I closed it by mistake 😅

**Comment by mathieujobin** [comment]
I am surprised you are not able to reopen your own PR. Could be a setting I don't know of.

Anyway, here you go...

**Review by mathieujobin — APPROVED** [review]

**Comment by PanosCodes** [comment]
Is there an reason for not merging this ? 😅

**Review by mathieujobin — APPROVED** [review]
I will be merging and releasing shortly.

Thanks for being patient...

**Pull request merged**
