### PR TITLE
Fix route discovery with api! for Rails 5 (passes tests)

### PR DESCRIPTION
**Pull request by aminariana**
I am building this PR on top of PR #465 from June 8, 2016. That one never made it to master because of bad Gemfile values that later got fixed in master, but never got merged into the PR.

In this PR:
- I fix the issue with api! route discovery by borrowing @sblackstone fix commit
- I add test coverage against Ruby 2.3.3
- I fix the failing tests by merging the latest Gemfile fixes from master into this PR

Travis is passing 100% for me locally.

Fixes Issue #415 
Fixes Issue #495 
Fixes Issue #510 
Distant relationship with Issue #522 
Related to PR #465

### CODE REVIEW

**Comment by iNecas** [comment]
Hi, I think I have a version that has actually tests passing with rails 5, will push in few minutes

**Comment by iNecas** [comment]
https://github.com/Apipie/apipie-rails/pull/527, finger crossed

**Comment by aminariana** [comment]
@iNecas My latest changes make it fully compatible with Rails 5.0 and Ruby 2.2.2+. However, I was forced to make it a breaking change, losing Rails <4 and Ruby <2.2. If yours is more compatible, great, if not please consider accepting this one.

**Comment by aminariana** [comment]
@iNecas by the way would be awesome to fix the Rails 5 deprecation warnings.

**Comment by iNecas** [comment]
I managed to keep it compatible in https://github.com/Apipie/apipie-rails/pull/527 (needed to drop ralis 32, but it was about a time), the deprecation warnings will be addressed separatly, such as here https://github.com/Apipie/apipie-rails/pull/420

**Comment by iNecas** [comment]
Closed by https://github.com/Apipie/apipie-rails/pull/527, thanks @aminariana, you helped a lot speeding up the process!

**Comment by jsantos** [comment]
Any hint why after this commit namespaced controllers would stop working?

I got the following error with this commit:

```
/.../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/inflector/methods.rb:268:in `const_get': uninitialized constant SurveyorUsersController (NameError)
  from /.../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/inflector/methods.rb:268:in `block in constantize'
  from /.../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/inflector/methods.rb:266:in `each'
  from /.../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/inflector/methods.rb:266:in `inject'
  from /.../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/inflector/methods.rb:266:in `constantize'
  from /.../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
  from /.../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/apipie-rails-d3519c357caf/lib/apipie/application.rb:58:in `route_app_controller'
  from /.../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/apipie-rails-d3519c357caf/lib/apipie/application.rb:64:in `block in routes_for_action'
  from /.../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/apipie-rails-d3519c357caf/lib/apipie/application.rb:63:in `select'
  from /.../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/apipie-rails-d3519c357caf/lib/apipie/application.rb:63:in `routes_for_action'
  from /.../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/apipie-rails-d3519c357caf/lib/apipie/apipie_module.rb:18:in `method_missing'
  from /.../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/apipie-rails-d3519c357caf/lib/apipie/method_description.rb:171:in `api_data'
  from /.../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/apipie-rails-d3519c357caf/lib/apipie/method_description.rb:26:in `initialize'
  from /.../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/apipie-rails-d3519c357caf/lib/apipie/application.rb:87:in `new'
  from /.../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/apipie-rails-d3519c357caf/lib/apipie/application.rb:87:in `block in define_method_description'
  from /.../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/apipie-rails-d3519c357caf/lib/apipie/application.rb:79:in `each'
  from /.../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/apipie-rails-d3519c357caf/lib/apipie/application.rb:79:in `define_method_description'
  from /.../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/apipie-rails-d3519c357caf/lib/apipie/apipie_module.rb:18:in `method_missing'
  from /.../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/apipie-rails-d3519c357caf/lib/apipie/dsl_definition.rb:408:in `method_added'
  from /.../my_rails_app/app/controllers/api/sms/surveyor_users_controller.rb:46:in `<class:SurveyorUsersController>'
  from /.../my_rails_app/app/controllers/api/sms/surveyor_users_controller.rb:1:in `<top (required)>'
```

It claims not to be able to find `SurveyorUsersController`, that in fact is `Api::Sms::SurveyorUsersController`.

**Comment by iNecas** [comment]
@jsantos seems like this code might be responsible for it https://github.com/Apipie/apipie-rails/pull/526/files#diff-c252ba104efd0ecb906ad2edd58ce884R58 ?

**Comment by jsantos** [comment]
@iNecas That's my best guess. 

I'm just wondering if there's anything wrong on my end, but before this commit (and on Rails 4.2.x) everything was running smooth. I was on the middle of the transition to Rails 5 and after upgrading apipie-rails to `0.4.0` bumped on this.

**Comment by iNecas** [comment]
@jsantos I will not get sooner to sending a fix for this until middle of this week: if you want to give it a try and fix it sooner, I will be more than happy to review.

**Comment by jsantos** [comment]
@iNecas Sure, I'll give it a shot 👍

**Comment by jsantos** [comment]
@iNecas Looks like this was a problem on our end (there was a route with no controller associated.

Shall we display a more informative error message when this happens?

**Comment by iNecas** [comment]
:+1: on that. Will you give it a try: it would be great, as you know what the reproducer was

**Comment by kklw** [comment]
Hi, on adding `api!`, I'm getting `NameError - uninitialized constant Api::V1::JobCreationsController:` .  Did i miss out something?

**Comment by jsantos** [comment]
@kklw Check if you have unused routes in your code. Doesn't need to be exactly the one that showed up in your stacktrace, but that was my case.

**Comment by kklw** [comment]
@jsantos Thanks! Works perfectly now.

**Comment by jsantos** [comment]
@iNecas Regarding this "issue" with non-existent routes: What's the best approach? Shall we present a clearer error message? 

Because continuing silently here doesn't look like a good practice, I'd say.

**Pull request closed without merging**
