### PR TITLE
A boolean parameters can be configured with both :bool and :boolean

### PR DESCRIPTION
**Pull request by Nerian**
A boolean parameters can be configured with both :bool and :boolean options. A boolean parameter can be any of: 'true', 'false', '1', '0'

### CODE REVIEW

**Comment by Pajk** [comment]
@Nerian @iNecas What do you think about this in 2015:)? I like the change and I don't think it should cause some serious troubles to anyone. Even if it does it will be mentioned in change log for next version so ppl will be aware of it.

**Comment by Nerian** [comment]
Awesome :+1:

**Comment by iNecas** [comment]
Aaaan v0.3.6 with this change has just been released

**Comment by iNecas** [comment]
Thanks for patience @Nerian  :)

**Comment by Nerian** [comment]
wooot!

**Pull request merged**
