### PR TITLE
Display engine path in documentation when using api!

### PR DESCRIPTION
**Pull request by neilgupta**
If my_engine is mounted at '/engine', ApiPie documentation will now
include "/engine" as part of the path when using api!

### CODE REVIEW

**Comment by neilgupta** [comment]
Any plans to merge this? Would be nice to get back on official branch :)

**Comment by Pajk** [comment]
@neilgupta Could you provide a working example or preferably include tests for this? Thanks!

**Comment by neilgupta** [comment]
Finally got around to adding specs for the engine mount path change... Unfortunately I also had to add a hack to workaround #415 that checks the Rails version to get the rails42 tests to pass. That clearly needs a better fix, but it falls outside the scope of this PR.

**Comment by iNecas** [comment]
Only 4 years to get this in, but it made it. Merged in https://github.com/Apipie/apipie-rails/pull/673

**Pull request closed without merging**
