### PR TITLE
test rails 5.0

### PR DESCRIPTION
**Pull request by mtparet**
- update rubies to last version
- test rails 5.0

### CODE REVIEW

**Comment by iNecas** [comment]
I suppose we should get it also fixed at the same PR, right?

**Comment by mtparet** [comment]
Indeed this is the goal. Also this will permit to check PRs/issues (and perhaps we could merge these in this one if needed) against Rails 5. #465 #481 #479 #473

**Comment by iNecas** [comment]
Ok, let's get this in to make the train moving

**Comment by iNecas** [comment]
The only thing is all the tests are failling on all rails versions now

**Comment by mtparet** [comment]
Yes, tests should passed before merging. (some works are required)

**Comment by raisin** [comment]
Rails 5.x.x.x has introduced several changes that impact apipie compatibility. I believe 13 compatibility issues need to be resolved before apipie will pass all the specs that have been written.

The following (forked) branch resolves 8 of these 13 issues. It isn't the most elegant code, but it illustrates how to fix these 8 issues.

https://github.com/raisin/apipie-rails/tree/raisin-rails-5.x-compatibility

If no one is actively working on this, I can improve the code and make it worthy of a pull request. 


Here is a breakdown of the remaining 5 issues.

For 2 of the remaining 5 issues, I wrote comments describing the problem within the branch linked above in this message.

That leaves 3 issues:
1.) spec/controllers/users_controller_spec.rb:295 - I worked on this issue but couldn't make progress. It would help to get feedback from someone familiar with apipie internals. It appears that a broadcast is made to multiple threads. It is unclear why that's being done.
2.) spec/controllers/apipies_controller_spec.rb:47 - I haven't investigated this one.
3.) spec/controllers/concerns_controller_spec.rb:25 - I haven't investigated this one, but it seems to require some insight into apipie internals. I suspect this is caused by the failure of the api! dsl directive. That in turn causes apis = [].

**Comment by mtparet** [comment]
Closing in favour of https://github.com/Apipie/apipie-rails/pull/527

**Comment by iNecas** [comment]
Aand it has been merged, the release will follow over the weekend

**Pull request closed without merging**
