### PR TITLE
Expect :number to have type 'numeric'

### PR DESCRIPTION
**Pull request by akofink**
WIP because I'm still testing

### CODE REVIEW

**Comment by akofink** [comment]
@mbacovsky this isn't working for me. Care to try it out?

```rb
Apipie.configuration.use_cache = false
Apipie.reload_documentation
Apipie.to_json("v2")[:docs][:resources]['activation_keys'][:methods][0][:params][0]

=> {:name=>"organization_id",
 :full_name=>"organization_id",
 :description=>"\n<p>organization identifier</p>\n",
 :required=>true,
 :allow_nil=>false,
 :allow_blank=>false,
 :validator=>"number.",
 :expected_type=>"string",
 :metadata=>nil,
 :show=>true,
 :validations=>[]}
```

Here's the [param definition](https://github.com/Katello/katello/blob/master/app/controllers/katello/api/v2/activation_keys_controller.rb#L20).

**Comment by mbacovsky** [comment]
@akofink, I finaly got to this. Pry revealed that there is another NumberValidator in Katello project [1] that takes precedence during validator look up. From the git history it seems the NumberValidator was added to Katello first and then added also to the Apipie.

:+1: from me for this patch. Thanks for the test.

To fix the original issue the redundant validator in Katello needs to be fixed or better removed from Katello completely to use the Apipie's validator with this patch.

[1] https://github.com/Katello/katello/blob/master/lib/katello/apipie/validators.rb#L32

**Comment by akofink** [comment]
Yay! Thank you for taking a look. I'm not sure why I didn't realize the validator was coming from Katello. Doh! ;)

**Comment by akofink** [comment]
@iNecas Could we please have a release with this change included?

**Comment by iNecas** [comment]
Apipie-rails-0.5.9 with this change has been pushed to Rubygems.

**Pull request merged**
