### PR TITLE
Update screenshots

### PR DESCRIPTION
**Pull request by wazery**
Just updating README screenshots.

### CODE REVIEW

**Comment by IlyaBylich** [comment]
Is it your private dropbox? I think it's better to put these static files to github (and to make sure that it's not included into gem package, of course)

**Comment by wazery** [comment]
Will do.

**Comment by wazery** [comment]
@iliabylich  Done.

**Comment by iliabylich** [comment]
:+1:

**Comment by iNecas** [comment]
Thanks

**Pull request merged**
