### PR TITLE
Fix layout path (Rails 4.2.5.1 compatibility)

### LINKED ISSUE #421: Broken after updating rails from 4.2.5 to 4.2.5.1
After updating rails from `4.2.5` to `4.2.5.1`, `apipie:cache` rake task started failing.

This change seems to be the cause:
https://github.com/rails/rails/commit/0c5c32aa7cea5ee1ea60bd1f87dfa5c7e7146a54

Release notes:
http://weblog.rubyonrails.org/2016/1/25/Rails-5-0-0-beta1-1-4-2-5-1-4-1-14-1-3-2-22-1-and-rails-html-sanitizer-1-0-3-have-been-released/

Error:
```
ActionView::MissingTemplate: Missing template ../../layouts/apipie/apipie with {:locale=>[:"en-dev"], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee]}. Searched in:
actionview-4.2.5.1/lib/action_view/path_set.rb:46:in `find'
actionview-4.2.5.1/lib/action_view/lookup_context.rb:121:in `find'
actionview-4.2.5.1/lib/action_view/renderer/abstract_renderer.rb:18:in `find_template'
actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:86:in `resolve_layout'
actionview-4.2.5.1/lib/action_view/renderer/template_renderer.rb:76:in `block in find_layout'
actionview-4.2.5.1/lib/action_view/lookup_context.rb:252:in `with_layout_format'
```

### PR DESCRIPTION
**Pull request by halilim**
Fixes #421 (Missing template ../../layouts/apipie/apipie ... error). Credits: @FooBarWidget's [comment](https://github.com/Apipie/apipie-rails/issues/421#issuecomment-177998315).

### CODE REVIEW

**Comment by iNecas** [comment]
Thanks @halilim

**Comment by laurynas** [comment]
:+1:

**Comment by domcleal** [comment]
Will this be released soon?

**Comment by iNecas** [comment]
v0.3.6 with this change has just been released. Thanks @halilim

**Pull request merged**
