### PR TITLE
Custom headers responses

### PR DESCRIPTION
**Pull request by PanosCodes**
### Why

To define custom response headers https://github.com/Apipie/apipie-rails/issues/706

### How

Extend the `Apipie::ResponseDescription::ResponseObject` with a header method

### Example

```ruby
api :GET, "/pets/:id/with-extra-details", "Get a detailed pet record"
returns code: 200, desc: "Detailed info about the pet" do
  param_group :pet
  property :num_legs, Integer, :desc => "How many legs the pet has"
  header 'Link', String, 'Relative links'
  header 'Current-Page', Integer, 'The current page', required: true
end

def show
  render JSON({ :pet_name => "Barkie", :animal_type => "iguana", :legs => 4 })
end
```

### CODE REVIEW

**Comment by davidwessman** [comment]
Is there anyway to use `array_of: DescriptionObject` that uses the https://github.com/Apipie/apipie-rails?tab=readme-ov-file#embedded-response-descriptions inside the `returns` block?

**Comment by PanosCodes** [comment]
You can delete this line 😅 https://github.com/Apipie/apipie-rails/blob/f300fcc27c7805bcce54b6e02d147bd15931ab12/lib/apipie/dsl_definition.rb#L436.

I'm not sure why it exists, there are no failing tests if it's removed 🤔

**Comment by davidwessman** [comment]
> You can delete this line 😅
> 
> https://github.com/Apipie/apipie-rails/blob/f300fcc27c7805bcce54b6e02d147bd15931ab12/lib/apipie/dsl_definition.rb#L436
> 
> .
> I'm not sure why it exists, there are no failing tests if it's removed 🤔

Hehe, that would be nice!

**Review by davidwessman — APPROVED** [review]
I like it! 🚀

**Comment by davidwessman** [comment]
@mathieujobin Any chance to get this merged?

**Review by mathieujobin — APPROVED** [review]

**Comment by mathieujobin** [comment]
Sorry for the delay here

**Comment by davidwessman** [comment]
No worries, thank you!

**Pull request merged**
