### PR TITLE
Only depends on railties and activemodel

### PR DESCRIPTION
**Pull request by mathieujobin**
Most of rails isn't required, and this gem should not bring all of it into minimalists apps, such as an API applications

includes #740

### CODE REVIEW

**Comment by mathieujobin** [comment]
@budnik Could you take a look at this please?

**Comment by themilkman** [comment]
@mathieujobin Regarding the required gems, you could take a look at: https://github.com/Apipie/apipie-rails/pull/729 
I also hope to reduce the dependencies.

**Comment by mathieujobin** [comment]
thanks @themilkman this is great as well
now, maybe I would like this one merge first because I am setting up github actions.
but if we can remove more after, that sounds good to me.

**Comment by themilkman** [comment]
I think `railties` should be replaced with  `actionpack` and `activesupport` in order to get rid of the other dependencies `railties` carries (in addition to those two). Not sure if `activemodel` is required (as you know my branch uses `actionview` which might not be required, too).
Anyway, as long as it works either solution would be better than the current state.

**Comment by mathieujobin** [comment]
@themilkman you are right ! `activemodel` doesn't appear to be required

taking `railties` only removes `thor` but sure, why not...

**Comment by ofedoren** [comment]
@mathieujobin don't we actually depend on `ActionView` as well? https://github.com/Apipie/apipie-rails/blob/85aa3b58ae25390811bc13847e020317aeed397c/lib/tasks/apipie.rake#L175

**Comment by themilkman** [comment]
I also reached this point and thought it should be necessary. Not sure why it works here anyway.

**Comment by ofedoren** [comment]
Well, I didn't get to test the deps dropping PR, I just remember that in rake tasks (which can be used in production) we use `ActionView` directly and AFAIK we don't have test for tasks or at least basic, but also not sure why didn't fail...

**Comment by mathieujobin** [comment]
@ofedoren @themilkman `actionview` is a dependency of `actionpack`.
That's why we don't need it explicitely.

**Comment by themilkman** [comment]
Ha, gotcha @mathieujobin, this time I was blind regarding the nested dependencies, great :)

**Pull request merged**
