### PR TITLE
Enable CI for Ruby on Rails 7.0

### PR DESCRIPTION
**Pull request by voxik**

### CODE REVIEW

**Comment by voxik** [comment]
And it fails:

~~~
FrozenError:
  can't modify frozen Array: ["/home/runner/work/apipie-rails/apipie-rails/spec/dummy/app/controllers", "/home/runner/work/apipie-rails/apipie-rails/spec/dummy/app/controllers/concerns", "/home/runner/work/apipie-rails/apipie-rails/spec/dummy/components/test_engine/app/controllers", "/home/runner/work/apipie-rails/apipie-rails/app/controllers", "/home/runner/work/apipie-rails/apipie-rails/app/helpers", "/home/runner/work/apipie-rails/apipie-rails/app/public"]
# ./vendor/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/engine.rb:574:in `unshift'
# ./vendor/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/engine.rb:574:in `block in <class:Engine>'
# ./vendor/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `instance_exec'
# ./vendor/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:32:in `run'
# ./vendor/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
# ./vendor/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:50:in `each'
# ./vendor/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:50:in `tsort_each_child'
# ./vendor/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:50:in `each'
# ./vendor/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:50:in `tsort_each_child'
# ./vendor/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/initializable.rb:60:in `run_initializers'
# ./vendor/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/application.rb:372:in `initialize!'
# ./vendor/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/railtie.rb:224:in `public_send'
# ./vendor/bundle/ruby/3.0.0/gems/railties-7.0.2.3/lib/rails/railtie.rb:224:in `method_missing'
# ./spec/dummy/config/environment.rb:8:in `<top (required)>'
# ./vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
# ./vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
# ./spec/spec_helper.rb:6:in `<top (required)>'
# ./vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
# ./vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
# ./spec/lib/validators/array_validator_spec.rb:1:in `<top (required)>'
~~~

I am observing the issues locally, that is why I thought I'll contribute this PR. But not really sure how to fix them :/

**Comment by mathieujobin** [comment]
I don't know either... what is freezing that array and why Rails's own initializer fails on it..

it sounds like the "boot order" has changed since the dummy app was created

**Comment by mathieujobin** [comment]
@voxik can you try modifying the config/environment file like this, it will tell you which initializer/middleware makes it fail.

image

**Comment by mathieujobin** [comment]
In the meantime, if that makes you feel better, I use this gem with Rails 7 app, and it works fine.
It's the dummy app inside the test suite that needs fixing

**Pull request merged**
