### PR TITLE
Improved support for multipart/form-data example recording

### PR DESCRIPTION
**Pull request by hossenlopp**
- Works with functional tests when the Content-Type is added to the request.env before calling the request.
  - i.e. `@request.env["CONTENT_TYPE"] = "multipart/form-data"`
- Is now able to format UploadedFiles from functional tests properly.
- Fixed formatting of Array and Boolean parameters.
  - These errored before from being treated as hashes.

### CODE REVIEW

**Comment by hossenlopp** [comment]
Has anyone gotten a chance to look at this? @iNecas @Pajk perhaps?

**Comment by iNecas** [comment]
Sorry for not getting to this earlier. I think I could find time for reviews now, but the PR should be rebased first, as there are conflicts right now

**Comment by robikovacs** [comment]
Hey @hossenlopp, do you have time to rebase this?

**Comment by butiricristian** [comment]
Hey @robikovacs I created an almost duplicate PR here #891 the only difference being some specs. Hope you can review it soon as it's become a pretty annoying issue on the project I'm working 😄

**Comment by hossenlopp** [comment]
@robikovacs Sorry I didn't notice your comment from December. This unfortunately is something I no longer have the bandwidth to work on. I am glad to see that @butiricristian has pulled over the changes on an updated branch. 😄

**Comment by robikovacs** [comment]
No worries @hossenlopp! Thank you, @butiricristian. I hope it get's merged 🤞

**Comment by mathieujobin** [comment]
closing in favor for #891

**Pull request closed without merging**
