### PR TITLE
Recursive globbing for controllers

### PR DESCRIPTION
**Pull request by baweaver**
Added a recursive glob to the default configuration to prevent the need to specify these things, and put the base url in for a more accurate result.

### CODE REVIEW

**Comment by iNecas** [comment]
Does this really work. AFAIK the @api_base_url is a hash (with versions as keys). But +1 for the globbing

**Comment by baweaver** [comment]
Yeah, granted. I'll patch that real quick. I assumed it was a string.

**Comment by baweaver** [comment]
Done, that should be safer.

**Comment by iNecas** [comment]
Thanks @baweaver. Merging now

**Comment by iNecas** [comment]
apipie-rails 0.3.2 with this fix was just release. Thanks @baweaver for the contribution!

**Pull request merged**
