### PR TITLE
Allow boolean array `[true, false]` to be a valid argument for BooleanValidator

### PR DESCRIPTION
**Pull request by PanosCodes**
### How

- Allow BooleanValidator to be build using `[true, false]` as argument.
- Remove the `[true, false]` handling from Swagger generator

____

It would probably be easier to review per commit

### CODE REVIEW

**Review by mjobin-mdsol — COMMENTED** [review]
Looks good, I'm slightly afraid this could introduce a breaking change... ?

**Comment by PanosCodes** [comment]
We can always put it behing and setting for example
```ruby
Apipie.configure do |config|
  config.validator.boolean.handle_boolean_array = false
end
```
My question is why use `[true, false]` in the first place instead of `:bool` or `:boolean` ?
If we deside to allow `[true, false]` passed as validator should we also allow `[1, 0]`

I'can't think any compelling reason and I'm leaning in closing this PR 😅 (we can use the tests refactoring in another PR)

**Comment by mathieujobin** [comment]
I don't know, we can keep it open for a while and wait if others wants to chime in their opinion.

**Review by mathieujobin — APPROVED** [review]
if you want to solve the conflict after the refactor, I will merge this as well.

**Comment by mathieujobin** [comment]
Thanks, I wasn't exactly sure about the spec removal...

**Pull request merged**
