### PR TITLE
ArgumentError (invalid byte sequence in UTF-8) #736

### PR DESCRIPTION
**Pull request by aussiDavid**
#736 ArgumentError (invalid byte sequence in UTF-8). Remove invalid characters when parsing the file handler path.

### CODE REVIEW

**Comment by mathieujobin** [comment]
@aussiDavid Can you rebase your branch so the tests run ? 

Thanks

**Comment by aussiDavid** [comment]
@mathieujobin Done.

**Comment by mathieujobin** [comment]
Merci David.

**Comment by ofedoren** [comment]
This rebase looks wierd, won't this mess up the already messed up history? :)

**Review by mathieujobin — CHANGES_REQUESTED** [review]
need to properly rebase, there has been a mix of merge and rebase, causing duplicate commits to be shown...

**Comment by aussiDavid** [comment]
I was unable to fix the rebasing. I've redone the pull request here https://github.com/Apipie/apipie-rails/pull/746

**Pull request closed without merging**
