### PR TITLE
Use AD::Reloader on Rails 4, app.reloader only on Rails 5+

### LINKED ISSUE #539: APIPie cannot load in rails 4.2.8
Under JRuby 9.1.8.0 with rails 4.2.8 with the default apipie.rb:
```
Apipie.configure do |config|
  config.app_name = "RailsPrisme"
  config.api_base_url = "/api"
  config.doc_base_url = "/apipie"
  # where is your API defined?
  config.api_controllers_matcher = "#{Rails.root}/app/controllers/**/*.rb"
end
````
The following URL (http://localhost:3000/apipie) yields:
```
undefined method `reloader' for #<RailsPrisme::Application:0x158a8ca7> Did you mean? reloaders

Rails.root: C:/work/va-ctt/rails/rails_prisme
apipie-rails (0.5.0) lib/apipie/application.rb:427:in `rails_mark_classes_for_reload'
apipie-rails (0.5.0) lib/apipie/application.rb:294:in `reload_documentation'
apipie-rails (0.5.0) lib/apipie/apipie_module.rb:18:in `method_missing'
apipie-rails (0.5.0) lib/apipie/application.rb:306:in `load_documentation'
apipie-rails (0.5.0) lib/apipie/apipie_module.rb:18:in `method_missing'
apipie-rails (0.5.0) app/controllers/apipie/apipies_controller.rb:31:in `block in index'
actionpack (4.2.8) lib/action_controller/metal/mime_responds.rb:212:in `respond_to'
apipie-rails (0.5.0) app/controllers/apipie/apipies_controller.rb:22:in `index'
actionpack (4.2.8) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
```

Thanks for your help.

Cris

### PR DESCRIPTION
**Pull request by domcleal**
Fixes #539 

(regression in 0.5.0 on Rails 4)

### CODE REVIEW

**Comment by iNecas** [comment]
Thanks @domcleal

**Comment by iNecas** [comment]
apipie-rails 0.5.1 released, including this change

**Comment by domcleal** [comment]
Thanks for the prompt release.

**Comment by cshupp1** [comment]
Thanks guys!

**Pull request merged**
