### PR TITLE
Add explanation for config cache_dir. / Add locale zh-CN zh-TW.

### PR DESCRIPTION
**Pull request by debbbbie**
Add explanation for `config.cache_dir`. Add locale `zh-CN` `zh-TW`

### CODE REVIEW

**Comment by iNecas** [comment]
Thanks @debbbbie  Could you swash the commits before I merge it?

**Comment by debbbbie** [comment]
@iNecas Do you mean commits title? How about now?

I feel excited about apipie, I't pretty!

**Comment by iNecas** [comment]
I meant this (see #365) getting all commits together using `git rebase -i`, if you're ok with this, I would close this PR, merge #365 (the content as well as code attribution stayed preserved)

**Comment by debbbbie** [comment]
@iNecas  done :smile_cat:

**Comment by debbbbie** [comment]
your mean is squash

**Comment by iNecas** [comment]
@debbbbie right, I haven't realized I have the typo in there, anyway, we understood each other at the end, so it's good, merging now, thanks!

**Comment by debbbbie** [comment]
:v:

**Pull request merged**
